# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.disk :disk, size: "33GB", primary: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.customize ['modifyvm', :id, '--paravirtprovider', 'kvm']
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provision "shell", path: "provision.sh"
end
