#!/usr/bin/expect -f

set timeout -1
spawn qemu-system-x86_64 \
		-kernel linux/arch/x86/boot/bzImage \
		-boot c \
		-m 2049M \
		-hda buildroot/output/images/rootfs.ext4 \
		-append "root=/dev/sda rw console=ttyS0,115200 acpi=off nokaslr" \
		-serial stdio \
		-display none \
		-enable-kvm
expect "login: "
send "root\n"
expect "#"
send "cd /\n"
expect "#"
send "rm -f /tux3.bin\n"
expect "#"
send "fallocate -l 50M /tux3.bin\n"
expect "#"
send "ls\n"
expect "tux3.bin"
send "./user/tux3 mkfs /tux3.bin\n"
expect "Make tux3 filesystem on /tux3.bin"
send "mount -t tux3 /tux3.bin /mnt\n"
send "df\n"
send "bonnie++ -d /mnt -s 10M -n 1 -m TUX3 -b -u root -q -z 420\n"
send "df\n"
send "rm -f /tux3.bin\n"
