# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "reproduction-btrfs"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.customize ['modifyvm', :id, '--paravirtprovider', 'kvm']
  end

end
