# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20220912.1"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'reproduction-btrfs'
    vb.cpus = "2"
    vb.memory = "1024"

    vb.customize ['modifyvm', :id, '--paravirtprovider', 'kvm']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '25GB'
  end

  config.vm.provision "shell", path: "provision.sh"
end
